broad:
  # 名称
  name: Broad
  # 版本
  version: 2.0.0
  # 开发者
  author: XingGao
  # 系统文件目录
  systemFileDir: ${user.home}/.broad-admin
  # 私钥
  privateKey: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAKY0Mj4bcHUrH6QYhwUxwuJMI9tYKJh+vL2g1ui8soVPsb0Sgt09kgp7mdrbn9cw64zmCpsAuquz6Y2io6/7QbU5rCGZz6aWRpk7MVaZeD4kWEnlIZAOPQu76v4XfQqzPZ+WyyPN/f0xCRZdRnOm+nRlwnujKqwOYcibMEfi+/mFAgMBAAECgYAUmVKCzQ7OjsYwpdOSKr0vI+WryUzavZZx4C3SkZSEnkB2oQU0G23uu6vxapfwaUFAaMB2vovkPPuc0MP9yyO0+U6k8n5OpPN8LKY0Fd/1BukLA2Jmz4kEgN1yXtdIlLhHVZS7xll8kwGPiHZDq5JPMHLL/8+ETLX3bKXX+QX8zwJBALcRRCeG4QBBYfLLg7hXEk8GQqLthVaHgTg3M2GhJpQfwIgS9AdiPUWnjSHrQ46J6yr6SHaWl4KzB+ZK/zNtOAMCQQDoawuNUXNVT6PrRIizZYEHakSD0z7tm/qwRPwq+QQAVCB147d4qFvqPfuzymCG8LF8JkfsyWd5+itrwEdZuKXXAkBXYO1n9HAWwB5xVgRkC2NYxsMtozNejsT1wRtMQS/5yYILMQi7MX/PbF7nzrRrJ5dQ5y+JMu3UW4GswSU4NaxjAkEAkbhb29TPnRN70Mx9cQ0ZIw8LuiM+dzeuq8n02PSb/6C/YWrO48WbK3iFUap3buOGRDK0Mc/tItspUjuSALz2rQJAF/grUEWwtldWs5aejUzYctPcfG/bqX2P4ipk5ZCDdkhe8vqyCr5EWKz3P/KPHjlZliMDZrA5lNgGB8x7SuFtFA==
  # 公钥
  publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCmNDI+G3B1Kx+kGIcFMcLiTCPbWCiYfry9oNbovLKFT7G9EoLdPZIKe5na25/XMOuM5gqbALqrs+mNoqOv+0G1Oawhmc+mlkaZOzFWmXg+JFhJ5SGQDj0Lu+r+F30Ksz2flssjzf39MQkWXUZzpvp0ZcJ7oyqsDmHImzBH4vv5hQIDAQAB

