# YAML data
server:
  port: 8000
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000
    threads:
      max: 800
      min-spare: 100

# Spring配置
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid,dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false
  cache:
    # 缓存类型
    type: redis
    #指定存活时间（ms）
    redis.time-to-live: 86400000
    #是否缓存空值，可以防止缓存穿透
    redis.cache-null-values: true
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB

# Sa-Token配置
sa-token:
  # token 名称 (同时也是cookie名称)
  token-name: Authorization
  # token 有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token 临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false


# 异步线程配置
async:
  executor:
    thread:
      # 配置核心线程数
      core-pool-size: 10
      # 配置最大线程数
      max-pool-size: 10
      # 配置队列大小
      queue-capacity: 1000
      # 配置线程池中的线程的名称前缀
      name:
        prefix: async-service-

# mybatis配置
mybatis-plus:
  type-aliases-package: com.broad.**.entity
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration:
    arg-name-based-constructor-auto-mapping: true
    map-underscore-to-camel-case: true
  #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# swagger配置 /doc.html
springfox:
  documentation:
    swagger-ui:
      enabled: true


# 安全配置（防XSS）
mica:
  xss:
    # 是否开启防XSS
    enabled: true
    # 拦截路由 例如: /**
    path-patterns:
      - /**
    # 是否开启防XSS
    path-exclude-patterns:
      - /static/**
      - /swagger-ui/**
      - /v2/api-docs/**


